- hosts: 127.0.0.1
  connection: local
  tasks:
    - name: Set Vault token for Consul usage
      ansible.builtin.lineinfile: 
        path: /root/OinkServer/env/consul.conf
        regexp: 'VAULT_TOKEN'
        line: VAULT_TOKEN="{{ lookup('file', mount_path + '/vault-persist/root_token') }}"
        state: present
    - name: Set Consul data dir
      ansible.builtin.lineinfile: 
        path: /etc/consul.d/consul-server.hcl
        regexp: 'data_dir ='
        line: data_dir = "{{ mount_path }}/consul-persist"
        state: present
    - name: Reload Consul Config
      ansible.builtin.systemd:
        name: consul.service
        state: restarted
        daemon_reload: yes
