# https://www.digitalocean.com/docs/volumes/resources/naming/
# https://www.digitalocean.com/docs/volumes/how-to/increase-size/

- hosts: 127.0.0.1
  connection: local
  tasks:
    - name: Find all attached volumes
      ansible.builtin.find:
        file_type: any
        paths: /dev/disk/by-id
        use_regex: yes
        patterns: '^scsi-0DO_Volume_(.*)$'
      register: result
    - name: Mount to volumes
      vars: 
        device_path: "{{ item.path }}"
        device_name: "{{ item.path | basename | regex_replace('^scsi-0DO_Volume_(.*)$', '\\1') | regex_replace('-', '_') }}"
      loop: "{{ result.files }}"
      include_tasks: mount-volume.tasks.yml
