- hosts: 127.0.0.1
  connection: local
  tasks:
    - name: Login to GCloud
      ansible.builtin.command:
        cmd: gcloud auth activate-service-account --project {{ GCP_PROJECT }} --key-file="{{ mount_path }}/terraform-persist/secret-writer.json"
  
    - name: Write Vault root token to GCloud Secret Manager
      ansible.builtin.command:
        cmd: gcloud secrets versions add {{ oinkcloud_region | upper }}_VAULT_ROOT --data-file="{{ mount_path }}/vault-persist/root_token"
    - name: Write Nomad root token to GCloud Secret Manager
      ansible.builtin.command:
        cmd: gcloud secrets versions add {{ oinkcloud_region | upper }}_NOMAD_ROOT --data-file="{{ mount_path }}/nomad-persist/root_token"
  
    - name: Write Consul CA public crt to GCloud Secret Manager
      ansible.builtin.command:
        cmd: gcloud secrets versions add {{ oinkcloud_region | upper }}_CONSUL_CA_CRT --data-file="{{ mount_path }}/vault-persist/server.dc1.consul-ca.crt"
    - name: Write Consul CA private key to GCloud Secret Manager
      ansible.builtin.command:
        cmd: gcloud secrets versions add {{ oinkcloud_region | upper }}_CONSUL_CA_KEY --data-file="{{ mount_path }}/vault-persist/server.dc1.consul-ca.key"
